# Generated by Django 4.2.5 on 2023-09-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Category'},
        ),
    ]
